version: "3"

services: 
  ##ref: https://github.com/shadowsocks/shadowsocks-libev/blob/master/docker/alpine/README.md 
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    ports:
      - "8388:8388"
    environment:
      - METHOD=chacha20-ietf-poly1305
      - PASSWORD=
    restart: always
